name: flutter_fingerprint_authentication
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  local_auth: ^2.1.2
  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
